name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build_job:
    runs-on: ubuntu-20.04
    name: build minishell
    steps:
      - uses: actions/checkout@v2
      - run: make
