name: norminette@v3
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  norminette_job:
    runs-on: ubuntu-20.04
    name: norminette
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - uses: JaeSeoKim/norminette-action@v3
        with:
          flags: "."
